name: updraft_sdk_flutter
description: "Updraft Flutter SDK project."
version: 0.0.1
homepage: https://github:com/appswithlove/updraft-sdk-flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appswithlove.updraft.updraft_sdk_flutter
        pluginClass: UpdraftSdkFlutterPlugin
      ios:
        pluginClass: UpdraftSdkFlutterPlugin
